version: '3.8'

services:
  # 1. Banco de Dados
  db:
    image: postgres:15
    container_name: postgres_container
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: senha123
      POSTGRES_DB: sistema_auth
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./src/scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - rmi-network

  # 2. Servidor RMI
  server:
    build: .
    container_name: rmi_server_container
    depends_on:
      - db
    ports:
      - "1099:1099"
    environment:
      - DB_URL=jdbc:postgresql://db:5432/sistema_auth
      - RMI_HOSTNAME=server
    command: sh -c "sleep 10 && java -Djava.rmi.server.hostname=server -jar app.jar"
    networks:
      - rmi-network

  # 3. Cliente Web
  client:
    build: .
    container_name: rmi_web_client
    depends_on:
      - server
    ports:
      - "8080:8080"
    environment:
      - SERVER_HOST=server
    command: sh -c "sleep 15 && java -cp app.jar com.exemplo.ClienteWeb"
    networks:
      - rmi-network

networks:
  rmi-network:
    driver: bridge

volumes:
  postgres_data: